import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Five Nights at Freddys',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="icon" type='image/png' href="/iconSite.png" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
